// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXqRlbj9mMM_EbSWaJ_sUfEJ6Fz9OiCOQ',
    appId: '1:42773556112:web:5dced9400ac4ea54606115',
    messagingSenderId: '42773556112',
    projectId: 'howaiu-7f904',
    authDomain: 'howaiu-7f904.firebaseapp.com',
    storageBucket: 'howaiu-7f904.appspot.com',
    measurementId: 'G-NS9M4XTWZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_pHrmv6iz5SMnqzGfkG3hRFxigzk5TPs',
    appId: '1:42773556112:android:aa66fefb2a028450606115',
    messagingSenderId: '42773556112',
    projectId: 'howaiu-7f904',
    storageBucket: 'howaiu-7f904.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAokJ82EHSUhjdgjJPYpB3P2BBphITU82Y',
    appId: '1:42773556112:ios:56fb22ff2479b263606115',
    messagingSenderId: '42773556112',
    projectId: 'howaiu-7f904',
    storageBucket: 'howaiu-7f904.appspot.com',
    iosClientId: '42773556112-ac98kniifk0t2um28eob849lh1sitv4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.howaiu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAokJ82EHSUhjdgjJPYpB3P2BBphITU82Y',
    appId: '1:42773556112:ios:56fb22ff2479b263606115',
    messagingSenderId: '42773556112',
    projectId: 'howaiu-7f904',
    storageBucket: 'howaiu-7f904.appspot.com',
    iosClientId: '42773556112-ac98kniifk0t2um28eob849lh1sitv4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.howaiu',
  );
}
